-- liquibase formatted sql
-- changeset ddrakhmanov@edu.hse.ru:1 -comment:Comment for team
-- validCheckSum: 9:913309550d59b90ca5394e7d22f22ae8
create table if not exists teams
(
    id          integer generated by default as identity primary key,
    shortname   varchar(50)  not null unique,
    fullname    varchar(100) not null unique,
    points      integer      not null,
    wins        integer      not null,
    loses       integer      not null,
    goalsscored integer      not null,
    goalsmissed integer      not null
    );
-- rollback delete teams;